FROM node:20

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY node_modules ./node_modules/
RUN npm rebuild

COPY scripts/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 3001

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "dev:docker"]
