services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
      APPS_DIR: ${APPS_DIR}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}   # vide = dépôts publics seulement
    volumes:
      - ${APPS_DIR}:/apps
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pontis_network
    ports:
      - "9000:9000" # A supprimer en prod, Traefik s'en chargera
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook.rule=Host(`hooks.pontis.ongoua.pro`)"
      - "traefik.http.routers.webhook.entrypoints=websecure"
      - "traefik.http.routers.webhook.tls=true"
      - "traefik.http.routers.webhook.tls.certresolver=letsencrypt"
      - "traefik.http.services.webhook.loadbalancer.server.port=9000"

networks:
  pontis_network:
    # external: true
